name: Automated Testing Workflow

on:
  # Triggers the workflow on push events to the 'main' branch
  push:
    branches: 
      - main
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      # Action to clone your repository content
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
         python-version: '3.13'

    - name: Install dependencies
      run: make install

    - name: Run pip-audit scan
      # This runs pip-audit on the installed environment.
      # The '--strict' flag ensures a non-zero exit code (failure) if vulnerabilities are found.
      run: make audit
      
    # This optional step shows the result in an easily readable format 
    - name: Summarize Audit Results
      if: always() # Run this step even if the previous step fails (due to vulnerabilities)
      run: make audit-report

  # Test: Runs pytest
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
         python-version: '3.13'

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test-unit

  # Test: Runs FastAPI API tests using Newman
  api-integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
         python-version: '3.12.3'

    # We need Node.js to run Newman
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.12.0'

    - name: Install Python Dependencies
      run: make install

    - name: Install Newman
      run: npm install -g newman

    - name: Run API Tests
      # This calls your working Makefile target
      run: make test-api
      
    # PRO TIP: Upload the server log if tests fail
    # This helps you debug why the API might have crashed in CI
    - name: Upload Server Log on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: server-test-log
        path: server_test.log