name: Python Dependency Audit

on:
  # Triggers the workflow on push events to the 'main' branch
  push:
    branches: 
      - main
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      # Action to clone your repository content
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
         python-version: '3.11.14'

    - name: Install dependencies
      run: make Install

    - name: Run pip-audit scan
      # This runs pip-audit on the installed environment.
      # The '--strict' flag ensures a non-zero exit code (failure) if vulnerabilities are found.
      run: make audit
      
    # This optional step shows the result in an easily readable format 
    - name: Summarize Audit Results
      if: always() # Run this step even if the previous step fails (due to vulnerabilities)
      run: make audit-report